### ISSUE TITLE
Can not delete data store crawler if parameter is too long

### ISSUE THREAD

**Issue by hoangvx** [codelibs/fess-ds-box#3]
![image](https://user-images.githubusercontent.com/24557490/229675005-93b048d1-3172-4a6c-97dd-71ad23bc5c2a.png)

I summited my parameter with length of 2001, then when saved its auto replace with cipher encrypt and become more than 4000 characters.

**Comment by marevol** [comment]
You can change form.admin.max.input.size in fess_config.properties.
Please see https://github.com/codelibs/fess/commit/51d98eb2e2f36d20cbf7c4284e321deead8bcf25
